package com.yk.booking.domain;

import static com.yk.booking.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ClientTierAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientTierAllPropertiesEquals(ClientTier expected, ClientTier actual) {
        assertClientTierAutoGeneratedPropertiesEquals(expected, actual);
        assertClientTierAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientTierAllUpdatablePropertiesEquals(ClientTier expected, ClientTier actual) {
        assertClientTierUpdatableFieldsEquals(expected, actual);
        assertClientTierUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientTierAutoGeneratedPropertiesEquals(ClientTier expected, ClientTier actual) {
        assertThat(actual)
            .as("Verify ClientTier auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientTierUpdatableFieldsEquals(ClientTier expected, ClientTier actual) {
        assertThat(actual)
            .as("Verify ClientTier relevant properties")
            .satisfies(a -> assertThat(a.getTierName()).as("check tierName").isEqualTo(expected.getTierName()))
            .satisfies(a ->
                assertThat(a.getDiscountPercentage())
                    .as("check discountPercentage")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDiscountPercentage())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientTierUpdatableRelationshipsEquals(ClientTier expected, ClientTier actual) {
        // empty method
    }
}
