package com.yk.booking.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TimeSlotAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeSlotAllPropertiesEquals(TimeSlot expected, TimeSlot actual) {
        assertTimeSlotAutoGeneratedPropertiesEquals(expected, actual);
        assertTimeSlotAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeSlotAllUpdatablePropertiesEquals(TimeSlot expected, TimeSlot actual) {
        assertTimeSlotUpdatableFieldsEquals(expected, actual);
        assertTimeSlotUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeSlotAutoGeneratedPropertiesEquals(TimeSlot expected, TimeSlot actual) {
        assertThat(expected)
            .as("Verify TimeSlot auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeSlotUpdatableFieldsEquals(TimeSlot expected, TimeSlot actual) {
        assertThat(expected)
            .as("Verify TimeSlot relevant properties")
            .satisfies(e -> assertThat(e.getStartTime()).as("check startTime").isEqualTo(actual.getStartTime()))
            .satisfies(e -> assertThat(e.getEndTime()).as("check endTime").isEqualTo(actual.getEndTime()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeSlotUpdatableRelationshipsEquals(TimeSlot expected, TimeSlot actual) {
        assertThat(expected)
            .as("Verify TimeSlot relationships")
            .satisfies(e -> assertThat(e.getCourt()).as("check court").isEqualTo(actual.getCourt()));
    }
}
